<?php

/**
 * @file
 * Simpletest mock module for Attached Assets testing.
 */

use Drupal\Core\Asset\AttachedAssetsInterface;

/**
 * Attached Assets Test: hook_js_alter().
 */
function attached_assets_test_js_alter(&$javascript, AttachedAssetsInterface $assets) {
  $file = drupal_get_path('module', 'attached_assets_test') . '/attached_assets_test.js';
  $javascript[$file] = $javascript['core/assets/vendor/jquery/jquery.min.js'];
  $javascript[$file]['data'] = $file;
}
