<?php

/**
 * @file
 * Simpletest mock module for Ajax forms testing.
 */

use Drupal\Core\Ajax;
use Drupal\Core\Ajax\AjaxResponse;
use Drupal\Core\Form\FormStateInterface;

/**
 * Attached Assets Test: hook_js_alter().
 */
function simpletest_js_alter(&$javascript, AttachedAssetsInterface $assets) {
  $file = drupal_get_path('module', 'attached_assets_test') . '/attached_assets_test.js';
  $javascript[$file] = $javascript['core/assets/vendor/jquery/jquery.min.js'];
  $javascript[$file]['data'] = $file;
}
